- name: Ensure Nessus agent is started
  ansible.builtin.systemd:
    name: nessusagent
    state: started
    enabled: yes
  listen: Start Nessus agent

- name: Enable Nessus agent service
  ansible.builtin.systemd:
    name: nessusagent
    enabled: yes
  listen: Enable Nessus agent
